gems:
  - jekyll-redirect-from
  
paginate: 6
permalink: /:title/

url: http://www.tamalesconpasaporte.com

authors:
  geo:
    name: Geo Perez
    image: /assets/images/geo.jpg
    bio: Desarrollador de software, amante de la cerveza (vivo en el pecado con ella), y deseoso de brincar de avión en avión.
  rox:
    name: Roxana Evans
    image: /assets/images/rox.jpg
    bio: Una de las cosas que no sabia que me gustaba tanto hasta que empece a hacerlo es viajar. Esa sensación que tienes al desconectarte de tu vida cotidiana y dedicarte conocer, comer y beber.
